site_name: 'Backstage Docs'

nav:
  - Home: index.md

plugins:
  - techdocs-core
  
markdown_extensions:
  pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
