apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api-demo
  description: Demonstrate OpenAPI in Backstage
spec:
  type: openapi
  lifecycle: experimental
  owner: backstage-demo-team
  definition: |
    ueyayuicafgidugfiayew
