app:
  baseUrl: ${BACKSTAGE_BASE_URL}
  analytics:
    ga:
      trackingId: ${ANALYTICS_TRACKING_ID}

backend:
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
  baseUrl: ${BACKSTAGE_BASE_URL}
  listen:
    host: 0.0.0.0
  cors:
    origin: ${BACKSTAGE_BASE_URL}
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # debug: true
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      ssl:
        rejectUnauthorized: false
  reading:
    allow:
      - host: '*.apps.stone.com.br'
      - host: '*.stg.dca.financialproducts.stone.com.br'
      - host: '*.platform.buy4.io'
      - host: '*.dc5.stg.apps.platform.buy4.io'

auth:
  environment: production
  providers:
    google:
      production:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

integrations:
  github:
    - host: github.com
      apps:
        - $include: github.yaml