app:
  baseUrl: http://localhost:3000
  title: Stone Backstage

organization:
  name: Stone

permission:
  enabled: true

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    upgrade-insecure-requests: false
    connect-src: ["'self'", 'http:', 'https:']
    script-src: ["'self'", "'unsafe-eval'", 'https://www.google-analytics.com']
    img-src: ["'self'", 'data:', 'https://www.google-analytics.com']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

scaffolder:

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:  
    type: 'googleGcs'
    googleGcs:
      bucketName: ${GCS_BUCKET_NAME}
      projectId: ${GOOGLE_PROJECT_ID}
      credentials: ${GOOGLE_APPLICATION_CREDENTIALS}

auth:
  provider: {}

catalog:
  # providers:
  #   github:
  #     platformCatalog:
  #       organization: 'platform-test-org'
  #       catalogPath: '.catalog/catalog.yaml'
  #       filters:
  #         branch: 'main'
  #         topic:
  #           include: ['sre-platform-generated']
  #           exclude: ['sre-platform-template'] 
  rules:
    - allow: [Component, System, API, Resource, Location, Group, User, Domain]
