apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: asyncapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: 
    $text: ./definition.yml
