apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  title: SRE-Platform Backstage
  description: Portal Backstage do projeto SRE-Platform
  namespace: stone-payments
  annotations:
    backstage.io/techdocs-ref: dir:../../
    # github.com/project-slug: stone-payments/backstage
  # links:
  #   - url: https://portal.platform.buy4.io/
  #     title: Portal
  #     icon: dashboard
  #   - url: https://docs.platform.buy4.io/backstage
  #     title: Site de Documentação
  #     icon: docs
spec:
  type: website
  lifecycle: production
  owner: sre-platform
  system: sre-platform
  dependsOn:
    - resource:backstage-db
    - resource:backstage-bucket
    - resource:sre-platform-control-cluster
